name: 'Check spelling'
on:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm install -D @cspell/dict-de-de
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: 'doc/**/*.md'
          root: '.'
          inline: warning
          suggestions: false
          strict: false
          config: '.cspell.config2.yaml'
          verbose: true
          report: all
          incremental_files_only: false
